apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  labels:
    app: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-microservice-worker   # ✅ Force sur le bon nœud
      containers:
        - name: bank-service
          image: mariammseddi12/bank-service:latest
          ports:
            - containerPort: 8021
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://bank-db-service:3306/bank_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_APPLICATION_NAME
              value: "BankService"
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip"
spec:
  selector:
    app: bank-service
  ports:
    - port: 8021
      targetPort: 8021
  type: LoadBalancer
  loadBalancerIP: 51.210.7.4
