apiVersion: apps/v1
kind: Deployment
metadata:
  name: reglementaffectation-service
  labels:
    app: reglementaffectation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reglementaffectation-service
  template:
    metadata:
      labels:
        app: reglementaffectation-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-microservice-worker
      containers:
        - name: reglemetnaffecatation-service
          image: mariammseddi12/reglemetnaffecatation-service:latest
          ports:
            - containerPort: 8025
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://reglemetnaffecatation-db-service:3306/reglemetnaffecatation_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: reglementaffectation-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip"
spec:
  selector:
    app: reglementaffectation-service
  ports:
    - port: 8025
      targetPort: 8025
  type: LoadBalancer
  loadBalancerIP: 51.210.7.4
